name: Publish all packages to NPM with auto-incremented patch release.

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.10
          registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install dependencies.
        run: pnpm install

      - name: Build all projects.
        run: pnpm build

      - name: Increment package version.
        run: pnpm increment-version

      - name: Publish packages.
        run: pnpm publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
